name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd packages/warp
          yarn
          yarn test

  publish-warp-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: |
          cp ./readme.md ./packages/warp/readme.md
          cd packages/warp
          yarn build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
  publish-create-warp-app-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: |
          cd packages/create-warp-app
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
